node:
  chain: local
  role: validator
  dataVolumeSize: 5Gi
  customNodeKey: "0000000000000000000000000000000000000000000000000000000000000002"
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  flags:
    - "--rpc-external"
    - "--ws-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-ws-external"
    - "--unsafe-rpc-external"
    - "--bob"
    - "--bootnodes '/dns4/alice-node-dscp-node-0-rc-p2p.alice.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'"
storageClass: standard
