logLevel: trace
userUri: //Alice
externalSqncNode:
  host: alice-node-sqnc-node-0
  port: 9944
externalSqncIpfs:
  host: alice-ipfs-sqnc-ipfs-api
  port: 5001
externalSqncIdentity:
  host: alice-identity-service-sqnc-identity-service
  port: 3000
ingress:
  hostname: localhost
  paths:
    - path: /alice/(v1/attachment(/.*)?)
      pathType: Prefix
    - path: /alice/(v1/demandA(/.*)?)
      pathType: Prefix
    - path: /alice/(v1/demandB(/.*)?)
      pathType: Prefix
    - path: /alice/(v1/match2(/.*)?)
      pathType: Prefix
    - path: /alice/(v1/transaction(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
node:
  enabled: false
