logLevel: debug
externalSqncNode:
  host: blue-node-sqnc-node-0
  port: 9944
externalSqncIpfs:
  host: ipfs-demandb-sqnc-ipfs-api
  port: 5001
externalSqncIdentity:
  host: demandb-identity-service-sqnc-identity-service
  port: 3000
auth:
  clientId: 'l3'
  publicUrlPrefix: "https://auth.sqnc-stage.com/realms/demandb/protocol/openid-connect"
  internalUrlPrefix: "http://keycloak.keycloak.svc.cluster.local/realms/demandb/protocol/openid-connect"
ingress:
  enabled: true
  ingressClassName: nginx-demandb
  hostname: demandb.sqnc-stage.com
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 15Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: demandb
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace