apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bob
resources:
  - source.yaml
  - dscp-node
configMapGenerator:
  - name: bob-values
    files:
      - values-dscp-node.yaml=dscp-node/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
