apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bob
resources:
  - source.yaml
  - sqnc-api
  - sqnc-identity-service
  - sqnc-node
  - inteli-api
  - ipfs-node
configMapGenerator:
  - name: bob-values
    files:
      - values-sqnc-node.yaml=sqnc-node/values.yaml
      - values-sqnc-ipfs.yaml=ipfs-node/values.yaml
      - values-sqnc-api.yaml=sqnc-api/values.yaml
      - values-sqnc-identity-service.yaml=sqnc-identity-service/values.yaml
      - values-inteli-api.yaml=inteli-api/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
