apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-sync
  namespace: monitoring
resources:
  - source.yaml
  - release.yaml
  - podmonitor.yaml
configMapGenerator:
  - name: monitoring-values
    files:
      - values.yaml
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomize-config.yaml
