apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    spec:
      version: "66.x"
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 10m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # driftDetection:
  #   mode: enabled
  #   ignore:
  #     # Ignore "validated" annotation which is not inserted during install
  #     - paths: [ "/metadata/annotations/prometheus-operator-validated" ]
  #       target:
  #         kind: PrometheusRule
  valuesFrom:
  # - kind: ConfigMap
  #   name: flux-kube-state-metrics-config
  #   valuesKey: kube-state-metrics-config.yaml
  - kind: ConfigMap
    name: monitoring-values
    valuesKey: values.yaml
