apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
resources:
  - release.yaml
  - source.yaml
configMapGenerator:
  - name: promtail-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomize-config.yaml
