logLevel: info
paths:
  - http://charlie-identity-service-sqnc-identity-service:3000/api-docs
  - http://charlie-sqnc-matchmaker-api:3000/api-docs
baseUrl:
  - http://localhost:3080/charlie/
apiPublicUrlPrefix: /charlie
oauthClientId: "charlie-swagger"
oauthAppName: "Charlie Swagger"
oauthUsePkce: true
ingress:
  hostname: localhost
  paths:
    - path: /charlie/(api-docs(/.*)?)
      pathType: Prefix
    - path: /charlie/(swagger(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
securitySchema:
  name: "oauth2"
  type: "oauth2"
  enabled: true
  oauth2:
    flows:
      - clientCredentials
    tokenUrl: "/auth/realms/charlie/protocol/openid-connect/token"
    refreshUrl: "/auth/realms/charlie/protocol/openid-connect/token"
    scopes: {}
