config:
  logLevel: info
  externalNodeHost: bob-node-dscp-node-0
  externalIpfsHost: bob-ipfs-dscp-ipfs-api
  externalIpfsPort: 5001
  accountKey: //Bob
  externalOrigin: "http://localhost:3080"
  externalPathPrefix: "bob/dscp-api"
ingress:
  paths:
    - "/bob/dscp-api/(.*)"
dscpIpfs:
  enabled: false
dscpNode:
  enabled: false
