node:
  chain: l3-sqnc
  role: validator
  dataVolumeSize: 100Gi
  perNodeServices:
    setPublicAddressToExternal:
      enabled: false
  keys:
    - type: "babe"
      scheme: "sr25519"
    - type: "gran"
      scheme: "ed25519"
  flags:
    - "--rpc-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"
    - "--prometheus-external"
    - "--state-pruning=2500000"
    - "--bootnodes '/dns4/magenta-sqnc-node-0-rc-p2p.capacity.svc.cluster.local/tcp/30333/p2p/12D3KooWDvUB5uBh6msz4D1Te3vkfiod9FyMwPvHM56W46c1osKk'"
  serviceMonitor:
    enabled: true
    namespace: order
storageClass: managed-csi-premium
