logLevel: info
selfAddress: 5Df4d56pDyPz3RM3RBLYC7nyhhL9mGXchrV1dkyYPt5u8H88
externalSqncNode:
  host: blue-node-sqnc-node-0
  port: 9944
auth:
  clientId: 'l3'
  publicUrlPrefix: "https://auth.dsch-l3.com/realms/order/protocol/openid-connect"
  internalUrlPrefix: "http://keycloak.keycloak.svc.cluster.local/realms/order/protocol/openid-connect"
ingress:
  enabled: true
  ingressClassName: nginx-order
  hostname: order.dsch-l3.com
node:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
