apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-values
  namespace: dscp
data:
  values.yaml: |
    configmap:
      hashSumEnabled: true
    service:
      proxy:
        enabled: false
      api:
        port: 80
    oathkeeper:
      managedAccessRules: false
      config:
        log:
          level: debug
          format: json
        serve:
          api:
            port: 4456
          prometheus:
            port: 9000
        errors:
          fallback:
            - json
          handlers:
            json:
              enabled: true
              config:
                verbose: true
        mutators:
          noop:
            enabled: true
        authorizers:
          allow:
            enabled: true
        authenticators:
          oauth2_introspection:
            enabled: true
            config:
              introspection_url: http://hydra-admin:4445/oauth2/introspect
              scope_strategy: wildcard
          noop:
            enabled: true
          
    ingress:
      proxy:
        enabled: false
      api:
        enabled: false
    maester:
      enabled: true
