logLevel: info
paths:
  - http://capacity-identity-service-sqnc-identity-service:3000/api-docs
  - http://capacity-matchmaker-api-sqnc-matchmaker-api:3000/api-docs
baseUrl:
  - https://capacity.dsch-l3.com
securitySchema:
  name: "oauth2"
  type: "oauth2"
  enabled: true
  oauth2:
    flows:
      - clientCredentials
    tokenUrl: "https://auth.dsch-l3.com/realms/capacity/protocol/openid-connect/token"
    refreshUrl: "https://auth.dsch-l3.com/realms/capacity/protocol/openid-connect/token"
    scopes: {}
ingress:
  ingressClassName: nginx-capacity
  enabled: false
  hostname: capacity.dsch-l3.com
  paths:
    - path: /(api-docs(/.*)?)
      pathType: Prefix
    - path: /(swagger(/.*)?)
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
